### ISSUE TITLE
Error: Unsupported argument -socks found. Setting SOCKS version isn't possible anymore, only SOCKS5 proxies are supported. (LOOP)

### ISSUE THREAD

**Issue by ghost** [Deviantcoin/Wallet#1]
Windows DeviantCoin Wallet:

First login worked and then clicked on proxy and restarted and got this message.

**Error: Unsupported argument -socksfound. Setting SOCKS version isn't possible anymore, only SOCKS5 proxies are supported.**

Kinda stuck now looking for the config setup in Appdata/Roaming/Deviant/ to reset this.

It does not work with deleting the deviant folder or the .exe or downloading it again after deleting it all.

The **Error** still appears as if a config file still exist around..

I'm not allowed into the wallet and go to settings after the **Error** appears .. everything closes.

Thanks

**edit:** fixed it with regedit on Windows

Computer/HKEY_CURRENT_USER/Software/Deviant/Deviant-Qt and turned **"fUseProxy"** **"false"**

https://bitcoin.stackexchange.com/questions/66546/having-trouble-with-a-new-wallet

**Comment by Saxtr0** [comment]
On linux such error is solved setting:
fUseProxy=false
in file $HOME/.config/Deviant/Deviant-Qt.conf
where $HOME belong to user that run the wallet

**Comment by ghost** [comment]
Hi friends, I found this when looking into the issue on another coin - I figured since this is first search result for this error on google, that I'd add windows fix for this:

Open regedit, by going to the start menu, search for the program called run, type in regedit after opening run into the box, then in the list to the left hand side of the program, find, hkey_currentuser, expand that and then expand the tab that says software, deviant, deviant-qt, and then for fuseproxy you input 'false' instead of 'true'

This same process works for most coins with the issue, include deviant, or at least, pre-swap deviant wallet. May no longer be relevant due to deviant swap.

**Comment by canalmvpi** [comment]
Deu certo com a Bitradio!!! Obrigado.
